apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    VALUE: AgAmMhUrHZ8wy5wcEOSp2J+ixroJyDykgxYWn/2X9g/aUtSau3c0uwAYTTft51Syy1NcB+aGeo8e1gnp3kkoztXoGz4N0qxsoeZx5qMMiUXlI75QHsdCj22mCatM4eW9dIH9j/6p+Disg9/9xvcyMxh4ahlw/L7a9W5wOj8+1EOh8WXkoDb+ojy8Vj2w3c5D4DdatR82WGrmnqC6tszz3rujluF4qs+I+e+kkYHC9wxLBE4EfAxTG7d4a3pfE2KgDVkoYbm5jJtI5l30aMYjBvtPNTJqz8g+83DVjjBYtNSrjZpZVTVzrePdjCYcMnlcP+BH0d4GKjpThyJukVTHsn9lP4uljFSdWU04tWEfmQc0hR3zyhx7pbpfllzuIjaLnEwyp/dI7vb5/hpsnExn8YUvxiQ4c0Wv6i2Ijw9+WbVqcCzm7rK5fHuRlW8Z2DOx+PdYWLERMMJWgtNXr6uE9KkQOMicz8MyQw+JJ+5xGlVPMiP7qaHSn+CyNCjp4dkPNKCqCvwt9hoai4snTAK1xvnsutSVfIy7GgOcf4B8vDXmviuTH9FMewHlxPO47dUQVWp4Cg0ip9BRUNwuFStUKPYaFoDMJkzGb69CN8qpp16q2b5gGorA0gWIeTmO9s1rXSj2O3c+id7HE70XlqJXEIDzt//ivt70uyJXtp3smhGDU6nWLoD5hACCFYEQKtHtxEgva3jigOoK/isKj9C/0G7iae7YXWNgzk0BYDw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default

